FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Corporate

API's for corporate integration of yatra mobile app(android) at controller level.

# Corporate API Root [/]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

It is recommend to follow the “url” link values,
[Link](https://tools.ietf.org/html/rfc5988) or Location headers where
applicable to retrieve resources. Instead of constructing your own URLs,
to keep your client decoupled from implementation details.

## Login Request [POST /login]
Controller login API accepts email and password as mandatory params.
+ email (string) - Email Id of User
+ password (string) - Password of User

+ Request (application/json)

        {
            "email": "abc@xyz.com",
            "password": "qwerty"
        }

+ Response 200 (application/json)

        {  
           "authToken":"5ad0d390-8838-48e2-88fb-08a6eda00929",
           "corporateName":"ABC Corporate",
           "Tabs":[  
              {  
                 "TabName":"Flights",
                 "TabDesc":"Book Domestic & International Flights"
              },
              {  
                 "TabName":"Approvals",
                 "TabDesc":"Check Your Approvals"
              },
              {  
                 "TabName":"My Bookings",
                 "TabDesc":"View Your Bookings"
              }
           ]
        }


## User Detail Request [POST /detail]
Gets logged in user detail as per mandatory login token id and method
+ tokenId (string) - token generated as login service response
+ method (string) - method to be called at service end

+ Request (application/json)

        {
            "tokenId": "5ad0d390-8838-48e2-88fb-08a6eda00929",
            "method": "getUserProfile"
        }

+ Response 200 (application/json)

        {  
           "userId":3093092,
           "address":[  
              {  
                 "label":"Name",
                 "value":"Ms firstName LastName"
              },
              {  
                 "label":"Login Email",
                 "value":"ytbookings2@gmail.com"
              },
              {  
                 "label":"Mobile Number",
                 "value":"+91-8985235678"
              }
           ],
           "details":[  
              {  
                 "label":"Employee Code",
                 "value":"39049"
              },
              {  
                 "label":"Cost Center",
                 "value":"7668"
              },
              {  
                 "label":"Project Code",
                 "value":"6678"
              }
           ],
           "freqFlyer":[  
              {  
                 "fc":"Al-213",
                 "ffn":"766969967698"
              },
              {  
                 "fc":"Al-213",
                 "ffn":"766969967698"
              },
              {  
                 "fc":"Al-213",
                 "ffn":"766969967698"
              }
           ]
        }

## Profile Request [POST /profile]
Gets logged in user detail as per mandatory login token id and method
+ tokenId (string) - token generated as login service response
+ method (string) - method to be called at service end

+ Request (application/json)

        {
            "tokenId": "5ad0d390-8838-48e2-88fb-08a6eda00929",
            "method": "getCorporateProfile"
        }

+ Response 200 (application/json)

        {  
           "address":{  
              "corporateId":"777",
              "companyName":"ABC Corporate Company",
              "streetAddress":"xyz",
              "streetAddress2":"abc",
              "city":"Bangalore",
              "state":"KA",
              "country":"India",
              "pincode":"803116",
              "contactPhone":{  
                 "countyCode":"+91",
                 "stateCode":"0124",
                 "phoneNumber":"3333400"
              },
              "logoURL":"https://yatra.com.img/1.jpg"
           },
           "additionalInfo":[  
              {  
                 "label":"Travel Adminstrator",
                 "value":[  
                    "Ms. Onika Thakur",
                    "onika.thakur@yatra.com"
                 ]
              },
              {  
                 "label":"Available Credit Limit",
                 "value":[  
                    "INR 20,00,000"
                 ]
              },
              {  
                 "label":"Yatra Sales Incharge",
                 "value":[  
                    "Mr. Lalit Singh",
                    "onika.thakur@yatra.com",
                    "+91-8985235261"
                 ]
              }
           ]
        }
        
## Logout Request [POST /logout]
Logs out user as per mandatory login token id and method
+ tokenId (string) - token passed for user to be logged out
+ method (string) - method to be called at service end

+ Request (application/json)

        {
            "tokenId": "5ad0d390-8838-48e2-88fb-08a6eda00929",
            "method": "getLogoutProfile"
        }

+ Response 200 (application/json)

        {
            "status":"200"
        }
        
## Forgot Password Request [POST /forgotPassword]
Logs out user as per mandatory login token id and method
+ email (string) - token passed for user to be logged out
+ method (string) - method to be called at service end

+ Request (application/json)

        {
            "email": "abc@xyz.com",
            "method": "getLogoutProfile"
        }

+ Response 200 (application/json)

        {
            "status":"200"
        }

## My Bookings Request [POST /mybooking]
Booking list for corporate user, mandatory login token id and method
+ email (string) - token passed for user to be logged out
+ method (string) - method to be called at service end

+ Request (application/json)

        {
            "tokenId": "5ad0d390-8838-48e2-88fb-08a6eda00929",
            "method": "myBookings"
        }

+ Response 200 (application/json)

        {  
           "trips":{  
              "upcoming":[  
                 {  
                    "startDate":"03/09/2015",
                    "bookingDate":"07/05/2015",
                    "status":"Upcoming",
                    "isReturn":"N",
                    "origin":"GOI",
                    "bookingType":"D",
                    "bookingMode":"online",
                    "pnr":"0705151073",
                    "endDate":"03/09/2015",
                    "miles":"9",
                    "productType":"flight",
                    "destination":"BOM",
                    "companyId":"YT",
                    "referenceNo":"14486172",
                    "travellerName":"Kumar Akash"
                 },
                 {  
                    "startDate":"03/09/2015",
                    "bookingDate":"07/05/2015",
                    "status":"Upcoming",
                    "isReturn":"N",
                    "origin":"GOI",
                    "bookingType":"D",
                    "bookingMode":"online",
                    "pnr":"0705151073",
                    "endDate":"03/09/2015",
                    "miles":"9",
                    "productType":"flight",
                    "destination":"BOM",
                    "companyId":"YT",
                    "referenceNo":"14486172",
                    "travellerName":"Kumar Akash"
                 }
              ],
              "cancelled":[  
                 {  
                    "startDate":"15/12/2015",
                    "bookingDate":"07/05/2015",
                    "status":"Cancelled",
                    "isReturn":"N",
                    "origin":"DEL",
                    "bookingType":"D",
                    "bookingMode":"online",
                    "pnr":"07051586867",
                    "endDate":"15/12/2015",
                    "miles":"11",
                    "productType":"flight",
                    "destination":"JAI",
                    "companyId":"YT",
                    "referenceNo":"14486420",
                    "travellerName":"Kumar Akash"
                 }
              ],
              "completed":[  
                 {  
                    "startDate":"24/04/2015",
                    "bookingDate":"28/11/2014",
                    "status":"Completed",
                    "isReturn":"N",
                    "origin":"HYD",
                    "bookingType":"D",
                    "bookingMode":"online",
                    "pnr":"281114290205",
                    "endDate":"24/04/2015",
                    "miles":"22",
                    "productType":"flight",
                    "destination":"BLR",
                    "companyId":"YT",
                    "referenceNo":"13603666",
                    "travellerName":"Kumar Akash"
                 }
              ]
           }
        }
        
## My Booking Details Request [POST /myBookingDetails]
Booking details of a corporate booking, mandatory login token id,reference No and method
+ email (string) - token passed for user to be logged out
+ referenceNo (string) - booking reference number
+ method (string) - method to be called at service end

+ Request (application/json)

        {
            "tokenId": "5ad0d390-8838-48e2-88fb-08a6eda00929",
            "referenceNo: "13603666", 
            "method": "getBookingDetails"
        }

+ Response 200 (application/json)
        
        {  
           "response":{  
              "flight":{  
                 "superPnr":"281114290205",
                 "tripType":"One Way",
                 "bookingType":"D",
                 "companyId":"YT",
                 "currencySymbol":"Rupees",
                 "bookingCartNumber":"CT111",
                 "flightInfo":[  
                    {  
                       "isPnrAppendedToURL":"false",
                       "contactNumber":"011 2565 2050",
                       "airLinesCode":"AI",
                       "URL":"https://flyai.mobi/itravel/occi.xhtml",
                       "isWebCheckinPrintoutRequired":"false",
                       "airLinesName":"Airindia"
                    }
                 ],
                 "legInfos":[  
                    {  
                       "departureCity":"Hyderabad",
                       "arrivalCity":"Bangalore",
                       "stops":"Non Stop",
                       "legDetails":[  
                          {  
                             "baggage":[  
                                {  
                                   "cabin":"7 Kg"
                                },
                                {  
                                   "checkin":"15 Kg"
                                }
                             ],
                             "departureTime":"24/04/2015 06:30",
                             "departureTerminal":"",
                             "arrivalTerminal":"",
                             "gdsPnr":"64DCKF",
                             "airlinePnr":"HX99S",
                             "arrivalDateTime":"2015-04-24T07:35+0530",
                             "arrivalCity":"Bangalore",
                             "yatraAirlineCode":"AI",
                             "departureCity":"Hyderabad",
                             "airlineCode":"AI",
                             "departureCityCode":"HYD",
                             "arrivalCityCode":"BLR",
                             "status":"Confirmed",
                             "departureDateTime":"2015-04-24T06:30+0530",
                             "airlineName":"Airindia",
                             "flightCode":"515",
                             "duration":"1:5",
                             "fareRule":"Refundable",
                             "fareType":"Corporate Fare"
                          }
                       ]
                    }
                 ],
                 "paxDetails":[  
                    {  
                       "title":"",
                       "firstName":"Gadepalliprasad",
                       "middleName":"",
                       "lastName":"Venkat",
                       "type":"Adult",
                       "status":"Confirmed"
                    },
                    {  
                       "title":"",
                       "firstName":"Venkat",
                       "middleName":"",
                       "lastName":"Prasad",
                       "type":"Child",
                       "status":"Confirmed"
                    },
                    {  
                       "title":"",
                       "firstName":"Prasad",
                       "middleName":"",
                       "lastName":"Gadepalli",
                       "type":"Infant",
                       "status":"Confirmed"
                    }
                 ],
                 "fareDetails":{  
                    "fareBreakup":[  
                       {  
                          "description":"Total Payable Amount",
                          "amount":"5736.00"
                       },
                       {  
                          "description":"Base fare (Adult x 1)",
                          "amount":1
                       },
                       {  
                          "description":"Base fare (Child x 1)",
                          "amount":1
                       },
                       {  
                          "description":"Base fare (Infant x 1)",
                          "amount":1000
                       },
                       {  
                          "description":"Taxes and surcharges",
                          "amount":"4735.00"
                       },
                       {  
                          "description":"Discount",
                          "amount":-1,
                          "fmtAmount":1
                       }
                    ]
                 }
              }
           }
        }

## Approval home Request [POST /approvalHome]
Approval of supervisor in corporate booking, mandatory login token id and method
+ email (string) - token passed for user to be logged out
+ method (string) - method to be called at service end

+ Request (application/json)

        {
            "tokenId": "5ad0d390-8838-48e2-88fb-08a6eda00929",
            "method": "getRequestApprovalDetails"
        }

+ Response 200 (application/json)

        {  
           "approvalRequest":[  
              {  
                 "startDate":"15/12/2015",
                 "bookingDate":"07/05/2015",
                 "isReturn":"N",
                 "origin":"DEL",
                 "bookingType":"D",
                 "bookingMode":"online",
                 "pnr":"07051586867",
                 "endDate":"15/12/2015",
                 "miles":"11",
                 "productType":"flight",
                 "destination":"JAI",
                 "companyId":"YT",
                 "referenceNo":"14486420",
                 "travellerName":"Kumar Akash",
                 "approvalStatus":"Declined"
              }
           ],
           "supervisor":[  
              {  
                 "startDate":"15/12/2015",
                 "bookingDate":"07/05/2015",
                 "isReturn":"N",
                 "origin":"DEL",
                 "bookingType":"D",
                 "bookingMode":"online",
                 "pnr":"07051586867",
                 "endDate":"15/12/2015",
                 "miles":"11",
                 "productType":"flight",
                 "destination":"JAI",
                 "companyId":"YT",
                 "referenceNo":"14486420",
                 "travellerName":"Kumar Akash"
              }
           ]
        }
        
## Approval detail Request [POST /approvalDetail]
Approval detail for corporate booking, mandatory login token id and method
+ email (string) - token passed for user to be logged out
+ referenceNo (string) - method to be called at service end
+ method (string) - method to be called at service end

+ Request (application/json)

        {
            "tokenId": "5ad0d390-8838-48e2-88fb-08a6eda00929",
            "referenceNo: "14486420",
            "method": "getBookingDetails"
        }

+ Response 200 (application/json)

        {  
           "approvalInfo":{  
              "approvalType":"Itenary",
              "approvalStatus":"Pending",
              "bookingStatus":"Pending",
              "requestDate":"24/04/2015 06:30",
              "approver":"Mr. Kumar Akash",
              "approverMailId":"k.ak@yt.com",
              "travelReason":"Training"
           },
           "flight":{  
              "superPnr":"281114290205",
              "tripType":"One Way",
              "bookingType":"D",
              "companyId":"YT",
              "currencySymbol":"Rupees",
              "requestId":"347992",
              "flightInfo":[  
                 {  
                    "isPnrAppendedToURL":"false",
                    "contactNumber":"011 2565 2050",
                    "airLinesCode":"AI",
                    "URL":"https://flyai.mobi/itravel/occi.xhtml",
                    "isWebCheckinPrintoutRequired":"false",
                    "airLinesName":"Airindia"
                 }
              ],
              "legInfos":[  
                 {  
                    "departureCity":"Hyderabad",
                    "arrivalCity":"Bangalore",
                    "stops":"Non Stop",
                    "legDetails":{  
                       "baggage":[  
                          {  
                             "cabin":"7 Kg"
                          },
                          {  
                             "checkin":"15 Kg"
                          }
                       ],
                       "departureTime":"24/04/2015 06:30",
                       "departureTerminal":"",
                       "arrivalTerminal":"",
                       "gdsPnr":"64DCKF",
                       "airlinePnr":"HX99S",
                       "arrivalDateTime":"2015-04-24T07:35+0530",
                       "arrivalCity":"Bangalore",
                       "yatraAirlineCode":"AI",
                       "departureCity":"Hyderabad",
                       "airlineCode":"AI",
                       "departureCityCode":"HYD",
                       "arrivalCityCode":"BLR",
                       "status":"Confirmed",
                       "departureDateTime":"2015-04-24T06:30+0530",
                       "airlineName":"Airindia",
                       "flightCode":"515",
                       "duration":"1:5",
                       "fareRule":"Refundable",
                       "fareType":"Corporate Fare"
                    }
                 }
              ]
           },
           "paxDetails":[  
              {  
                 "title":"",
                 "firstName":"Gadepalliprasad",
                 "middleName":"",
                 "lastName":"Venkat",
                 "type":"Adult",
                 "status":"Confirmed"
              },
              {  
                 "title":"",
                 "firstName":"Venkat",
                 "middleName":"",
                 "lastName":"Prasad",
                 "type":"Child",
                 "status":"Confirmed"
              },
              {  
                 "title":"",
                 "firstName":"Prasad",
                 "middleName":"",
                 "lastName":"Gadepalli",
                 "type":"Infant",
                 "status":"Confirmed"
              }
           ],
           "fareDetails":{  
              "fareBreakup":[  
                 {  
                    "description":"Total Payable Amount",
                    "amount":"5736.00"
                 },
                 {  
                    "description":"Base fare (Adult x 1)",
                    "amount":1
                 },
                 {  
                    "description":"Base fare (Child x 1)",
                    "amount":1
                 },
                 {  
                    "description":"Base fare (Infant x 1)",
                    "amount":1000
                 },
                 {  
                    "description":"Taxes and surcharges",
                    "amount":"4735.00"
                 },
                 {  
                    "description":"Discount",
                    "amount":-1,
                    "fmtAmount":1
                 }
              ]
           }
        }